
import { environment } from "../../../../environments/environment"
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.5.0 (NJsonSchema v10.0.27.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpResponseBase } from '@angular/common/http';
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class BillServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = environment.apiUrl;
    }

    createBill(billType:any,bill: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/Bill/addWithPermission?id="+billType, bill);
    }
    deleteListBill(bill: any): Observable<number> {
        return this.http.post<any>(environment.apiUrl + "/api/Bill/deleteList?", bill);
    }
    updateBill(billType,bill: any): Observable<any> {
        return this.http.post<any>(environment.apiUrl + "/api/Bill/editWithPerssion?id="+billType, bill);
    }
    getDdl(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/Bill/get-ddl?");
    }
    getAllNotGeneratedEntryBills(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/Bill/getNotGeneratedEntryBills?");
    }
    GetBillPaymentsByParams(payWay:any,billKind:any,customerId:any,supplierId:any): Observable<any> {
          
        let params = new HttpParams();
        params = params.append('PayWay', payWay);
        params = params.append('BillKind', billKind);
        params = params.append('CustomerId', customerId);
        params = params.append('SupplierId', supplierId);

        return this.http.get<any>(this.baseUrl + "/api/Bill/GetBillPayments?", { params: params });
    }
    GetBillPaidByParams(payWay:any,billKind:any,customerId:any,supplierId:any): Observable<any> {
          
        let params = new HttpParams();
        params = params.append('PayWay', payWay);
        params = params.append('BillKind', billKind);
        params = params.append('CustomerId', customerId);
        params = params.append('SupplierId', supplierId);

        return this.http.get<any>(this.baseUrl + "/api/Bill/GetBillPaid?", { params: params });
    }
  
    allBills(pageIndex: number | undefined, pageSize: number | undefined, sortBy: string | undefined, sortOrder: string | undefined, filter: string | undefined): Observable<any> {
     
        let queryParams = new HttpParams();
        if (pageIndex != undefined)
            queryParams = queryParams.append("pageIndex", pageIndex);
        if (pageSize != undefined)
            queryParams = queryParams.append("pageSize", pageSize);
        if (sortBy != undefined)
            queryParams = queryParams.append("sortBy", sortBy);
        if (sortOrder != undefined)
            queryParams = queryParams.append("sortOrder", sortOrder);
        if (filter != undefined)
            queryParams = queryParams.append("filter", filter);

        return this.http.get<any>(this.baseUrl + "/api/Bill/all?", { params: queryParams });

    }


    getBill(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(this.baseUrl + "/api/Bill/getById", { params: params });
    }
    getLastCode(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/Bill/getLastCode?");
    }
    getLastCodeByTypeId(typeId:any): Observable<any> {
        let params = new HttpParams();
        params = params.append('typeId', typeId);
        return this.http.get<any>(this.baseUrl + "/api/Bill/getLastCodeByTypeId", { params: params });
    }
    deleteBill(billType:any, billId: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('billId', billId);
        params = params.append('id', billType);
        return this.http.delete<any>(environment.apiUrl + "/api/Bill/deleteWithPermission", { params: params });
    }
    deleteEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/Bill/deleteEntity?", entity);
    }
    deleteListEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/Bill/deleteListEntity?", entity);
    }
    
    checkPrintPermission(billType:any): Observable<any> {
        return this.http.get<any>(environment.apiUrl + "/api/Bill/checkPrint?id="+billType);
    }
    generateEntry(list: any): Observable<number> {
        return this.http.post<any>(environment.apiUrl + "/api/Bill/generateEntry?", list);
    }

}

