
import { environment } from "../../../../environments/environment"
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.5.0 (NJsonSchema v10.0.27.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');
import {BillDynamicDeterminantList, InsertBillDynamicDeterminant} from '../models/bill-dynamic-determinant';
@Injectable({
    providedIn: 'root'
})
export class ItemCardServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = environment.apiUrl;
    }

    createItemCard(ItemCard: any): Observable<any> {
        
        return this.http.post<any>(environment.apiUrl + "/api/ItemCard/add?", ItemCard);
    }
    
   
    deleteListItemCard(ItemCard: any): Observable<number> {
        return this.http.post<any>(environment.apiUrl + "/api/ItemCard/deleteList?", ItemCard);
    }
    updateItemCard(ItemCard: any): Observable<any> {
        
        return this.http.post<any>(environment.apiUrl + "/api/ItemCard/edit?", ItemCard);
    }
    getDdl(): Observable<any> {
        return this.http.get<any>(environment.apiUrl + "/api/ItemCard/get-ddl?");
    }
  
    allItemCards(pageIndex: number | undefined, pageSize: number | undefined, sortBy: string | undefined, sortOrder: string | undefined, filter: string | undefined): Observable<any> {
     
        let queryParams = new HttpParams();
        if (pageIndex != undefined)
            queryParams = queryParams.append("pageIndex", pageIndex);
        if (pageSize != undefined)
            queryParams = queryParams.append("pageSize", pageSize);
        if (sortBy != undefined)
            queryParams = queryParams.append("sortBy", sortBy);
        if (sortOrder != undefined)
            queryParams = queryParams.append("sortOrder", sortOrder);
        if (filter != undefined)
            queryParams = queryParams.append("filter", filter);

        return this.http.get<any>(this.baseUrl + "/api/ItemCard/all?", { params: queryParams });

    }


    getItemCard(id: any): Observable<any> {
        
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(this.baseUrl + "/api/ItemCard/getById", { params: params });
    }
    getLastCode(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/ItemCard/getLastCode?");
    }
    getLastCodeByItemGroupId(itemGroupId:any): Observable<any> {
        let params = new HttpParams();
        params = params.append('itemGroupId', itemGroupId);
        return this.http.get<any>(this.baseUrl + "/api/ItemCard/getLastCodeByItemGroupId", { params: params });
    }
    deleteItemCard(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(environment.apiUrl + "/api/ItemCard/delete", { params: params });
    }
    
    deleteEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/ItemCard/deleteEntity?", entity);
    }
    deleteListEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/ItemCard/deleteListEntity?", entity);
    }
    uploadFile(formData ):Observable<any>{
        return this.http.post<any>(environment.apiUrl + "/api/UploadFile/FileUpload", formData);
    }
    getBillDynamicDeterminant( billItemId: number | undefined, itemCardId: number | undefined): Observable<any> {
     
        let queryParams = new HttpParams();
      
        if (billItemId != undefined)
            queryParams = queryParams.append("billItemId", billItemId);
        if (itemCardId != undefined)
            queryParams = queryParams.append("itemCardId", itemCardId);
           

        return this.http.get<any>(this.baseUrl + "/api/Bill/getBillDynamicDeterminant?", { params: queryParams });

    }
    insertBillDynamicDeterminant(entity: InsertBillDynamicDeterminant): Observable<any> {

        return this.http.post<InsertBillDynamicDeterminant>(environment.apiUrl + "/api/Bill/insertBillDynamicDeterminant?", entity);
    }
}

