
import { environment } from "../../../../environments/environment"
/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.1.5.0 (NJsonSchema v10.0.27.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { WarehousesUnitDto, CreateWarehousesUnit , DeleteListWarehousesUnit , EditWarehousesUnit  } from '../models/warehouses-unit'
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class WarehousesUnitServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = environment.apiUrl;
    }

    createWarehousesUnit(currency: CreateWarehousesUnit ): Observable<WarehousesUnitDto> {

        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/add?", currency);
    }
    // ids: number[] | undefined;
    deleteListWarehousesUnit(currency: DeleteListWarehousesUnit ): Observable<number> {
        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/deleteList?", currency);
    }
    updateWarehousesUnit(currency: EditWarehousesUnit ): Observable<WarehousesUnitDto> {
        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/edit?", currency);
    }
    getDdl(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/get-ddl?");
    }
    all(pageIndex: number | undefined, pageSize: number | undefined, sortBy: string | undefined, sortOrder: string | undefined, filter: string | undefined): Observable<any> {
        let queryParams = new HttpParams();
        if (pageIndex != undefined)
            queryParams = queryParams.append("pageIndex", pageIndex);
        if (pageSize != undefined)
            queryParams = queryParams.append("pageSize", pageSize);
        if (sortBy != undefined)
            queryParams = queryParams.append("sortBy", sortBy);
        if (sortOrder != undefined)
            queryParams = queryParams.append("sortOrder", sortOrder);
        if (filter != undefined)
            queryParams = queryParams.append("filter", filter);

        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/all?", { params: queryParams });

    }


    getWarehousesUnit(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/getById", { params: params });
    }
    getLastCode(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/getLastCode?");
    }
    deleteWarehousesUnit(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(environment.apiUrl + "/api/WarehousesUnit/delete-warehousesUnit", { params: params });
    }

    deleteListWarehousesUnitTransaction(customer: any): Observable<any> {
        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/deleteListTransaction?",customer);
    }
    updateWarehousesUnitTransaction(customer: any): Observable<any> {
        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/editTransaction?",customer);
    }
    deleteWarehousesUnitTransaction(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(environment.apiUrl + "/api/WarehousesUnit/deleteTransaction", { params: params });
    }
    getWarehousesUnitTransaction(id: any): Observable<any> {
        let params = new HttpParams();
        params = params.append('id', id);
        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/getByIdTransaction", { params: params });
    }
    createWarehousesUnitTransaction(customer: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/addTransaction?",customer);
    }


    getCurrenciesTransactions(): Observable<any> {
        return this.http.get<any>(this.baseUrl + "/api/WarehousesUnit/get-ddl-warehouses-units-transactions?");
    }

    deleteEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/deleteEntity?", entity);
    }
    deleteListEntity(entity: any): Observable<any> {

        return this.http.post<any>(environment.apiUrl + "/api/WarehousesUnit/deleteListEntity?", entity);
    }

}

