export class SettingMenuShowOptions
{
    showCurrentTrack?:boolean;
    showFollowObject?:boolean;
    showWASL?:boolean;
    showCommands?:boolean;
    showHighlightInColor?:boolean;
    showOptions?:boolean;
    showSensors?:boolean;
    showSensorTracking?:boolean;
    showMedia?:boolean;
    showTemporaryBlocking?:boolean;
    showClone?:boolean;
    showDelete?:boolean;

    showDrivers?:boolean;
    showBlockEngine?:boolean;
    showUnblockEngine?:boolean;
    showDataRecalc?:boolean;
    showRoute?:boolean;
    showEdit?:boolean;
    showDeviceGeofence?:boolean;
    showDeviceNotification?:boolean;
    showUserDevice?:boolean;
    showUserGroup?:boolean;
    showUserDriver?:boolean;
    showUserGeofence?:boolean;
    showUserNotification?:boolean;
    showUserRoute?:boolean;
    showUserCity?:boolean;
    showPilotIntegration?:boolean;
    showDeviceComputedAttribute?:boolean;
    showWaslGroup?:boolean;
    showSendCommand?:boolean;
    showWaslLog?:boolean;
    showSelectGroup?:boolean;
    showSelectItem?:boolean;
    showDeleteGroup?:boolean;
    showSensorDevices?:boolean;
    showRegisterWaslCustomerDevices?:boolean;
    showRegisterWaslCustomerDrivers?:boolean;
    showRegisterAllDevices?:boolean;
    showRegisterAllDrivers?:boolean;
    showRegisterItem?:boolean;
    showAdminPanelPermission?:boolean;
    showAddGroup?:boolean;
    showAddItem?:boolean;
    showRegisterCustomer?:boolean;
    showUnRegisterCustomer?:boolean;
    showQueryCustomer?:boolean;
    showUnRegisterDevice?:boolean;
    showQueryDevice?:boolean;
    showUnRegisterDriver?:boolean;
    showQueryDriver?:boolean;
    showUnAssignSensorFromDevice?:boolean;
    showActivate?:boolean;
    showDetermineTheTechnician?:boolean;
    showRequestDetails?:boolean;
    showProductReceipt?:boolean;
    showPriceRequest?:boolean;
    showCloseRequest?:boolean;


}
